"""
Plotly Dash dependency-graph viewer generator.

Produces a self-contained Python script that launches a local Dash server with:
  • Full Graph (3D)       — all nodes and edges
  • Functional Tree (3D) — classes/functions/methods with calls+inherits only

Run the output file:  python <output_path>
Then open:            http://localhost:8050
"""

import json
import random
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Layout helpers (run at generation time, positions embedded in output)
# ─────────────────────────────────────────────────────────────────────────────

def _compute_layout(nodes: list, links: list, mode: str = "full", seed: int = 42) -> dict:
    """
    Returns {node_id: [x, y, z]} using networkx spring layout.
    Falls back to spherical random layout if networkx is unavailable.
    """
    import math

    if mode == "func":
        func_types = {"class", "function", "method"}
        vis_ids = {n["id"] for n in nodes if n["type"] in func_types}
        edge_pairs = [
            (l["source"], l["target"])
            for l in links
            if l["type"] in ("calls", "inherits")
            and l["source"] in vis_ids
            and l["target"] in vis_ids
        ]
        node_ids = list(vis_ids)
    else:
        node_ids = [n["id"] for n in nodes]
        vis_ids = set(node_ids)
        edge_pairs = [(l["source"], l["target"]) for l in links]

    if not node_ids:
        return {}

    try:
        import networkx as nx

        G = nx.Graph()
        G.add_nodes_from(node_ids)
        G.add_edges_from(
            (s, t) for s, t in edge_pairs if s in vis_ids and t in vis_ids
        )
        # Cap iterations for large graphs
        iters = 20 if len(G.nodes) > 300 else 40
        k_val = max(1.0, 2.0 / max(1, len(G.nodes) ** 0.3))
        pos = nx.spring_layout(G, k=k_val, iterations=iters, seed=seed, dim=3)
        scale = 20.0
        return {nid: [float(c) * scale for c in coords] for nid, coords in pos.items()}
    except ImportError:
        pass
    except Exception:
        pass

    # Fallback: distribute uniformly on a sphere
    rng = random.Random(seed)
    result = {}
    for i, nid in enumerate(node_ids):
        phi = math.acos(1 - 2 * (i + 0.5) / max(len(node_ids), 1))
        theta = math.pi * (1 + 5 ** 0.5) * i
        r = 20.0
        result[nid] = [
            r * math.sin(phi) * math.cos(theta),
            r * math.sin(phi) * math.sin(theta),
            r * math.cos(phi),
        ]
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Dash app template
# Characters __NODES__, __LINKS__, __POS_FULL__, __POS_FUNC__ are replaced.
# ─────────────────────────────────────────────────────────────────────────────

_TEMPLATE = r"""#!/usr/bin/env python3
# Faultline Dependency Graph — generated by Faultline
# Run:  python THIS_FILE
# Open: http://localhost:8050

import sys, json

try:
    import dash
    from dash import dcc, html, Input, Output, State, ctx
    import plotly.graph_objects as go
except ImportError:
    print("Missing dependencies. Install with:")
    print("  pip install dash plotly")
    sys.exit(1)

# ── Embedded graph data ───────────────────────────────────────────────────────
NODES    = __NODES__
LINKS    = __LINKS__
POS_FULL = __POS_FULL__
POS_FUNC = __POS_FUNC__

# ── Visual constants ──────────────────────────────────────────────────────────
NODE_COLORS = {
    "file":     "#4dabf7",
    "class":    "#51cf66",
    "function": "#ffd43b",
    "method":   "#ff922b",
}
BROKEN_COLOR   = "#ff3333"
AFFECTED_COLOR = "#ff7070"
EDGE_COLORS = {
    "contains": "rgba(100,100,100,0.15)",
    "imports":  "rgba(88,166,255,0.45)",
    "calls":    "rgba(255,140,66,0.60)",
    "inherits": "rgba(217,122,255,0.65)",
}
EDGE_WIDTHS = {"contains": 0.5, "imports": 1.0, "calls": 2.0, "inherits": 2.0}
NODE_SIZES  = {"file": 11, "class": 9, "function": 6, "method": 5}
FUNC_TYPES  = {"class", "function", "method"}

BG      = "#0d1117"
SURFACE = "#161b22"
BORDER  = "#30363d"
TEXT    = "#c9d1d9"
DIM     = "#6e7681"
ACCENT  = "#58a6ff"

# ── Precomputed lookups ───────────────────────────────────────────────────────
node_map = {n["id"]: n for n in NODES}
counts   = {}
for _n in NODES:
    counts[_n["type"]] = counts.get(_n["type"], 0) + 1

rev_adj = {n["id"]: [] for n in NODES}
for _l in LINKS:
    if _l["type"] != "contains":
        rev_adj.setdefault(_l["target"], []).append(_l["source"])


def bfs_affected(broken_ids):
    broken  = set(broken_ids)
    visited = set(broken)
    queue   = list(broken)
    while queue:
        nid = queue.pop(0)
        for dep in rev_adj.get(nid, []):
            if dep not in visited:
                visited.add(dep)
                queue.append(dep)
    return visited - broken


# ── Figure builder ────────────────────────────────────────────────────────────
def build_figure(view, broken_ids, search_term=""):
    broken_set   = set(broken_ids)
    affected_set = bfs_affected(broken_set)

    if view == "func":
        vis_nodes = [n for n in NODES if n["type"] in FUNC_TYPES]
        vis_ids   = {n["id"] for n in vis_nodes}
        vis_links = [
            l for l in LINKS
            if l["type"] in ("calls", "inherits")
            and l["source"] in vis_ids
            and l["target"] in vis_ids
        ]
        pos = POS_FUNC
    else:
        vis_nodes = list(NODES)
        vis_ids   = {n["id"] for n in vis_nodes}
        vis_links = list(LINKS)
        pos = POS_FULL

    if search_term:
        sl        = search_term.lower()
        vis_nodes = [n for n in vis_nodes if sl in n["label"].lower()]
        vis_ids   = {n["id"] for n in vis_nodes}
        vis_links = [
            l for l in vis_links
            if l["source"] in vis_ids and l["target"] in vis_ids
        ]

    fig = go.Figure()

    # Edge traces grouped by type
    edge_groups = {}
    for l in vis_links:
        t = l["type"]
        if t not in edge_groups:
            edge_groups[t] = {"x": [], "y": [], "z": []}
        sp = pos.get(l["source"], [0, 0, 0])
        tp = pos.get(l["target"], [0, 0, 0])
        edge_groups[t]["x"] += [sp[0], tp[0], None]
        edge_groups[t]["y"] += [sp[1], tp[1], None]
        edge_groups[t]["z"] += [sp[2], tp[2], None]

    for etype, coords in edge_groups.items():
        fig.add_trace(go.Scatter3d(
            x=coords["x"], y=coords["y"], z=coords["z"],
            mode="lines",
            line=dict(
                color=EDGE_COLORS.get(etype, "rgba(150,150,150,0.3)"),
                width=EDGE_WIDTHS.get(etype, 1.0),
            ),
            name=etype,
            legendgroup=f"edge_{etype}",
            showlegend=True,
            hoverinfo="none",
        ))

    # Node traces grouped by type
    node_groups = {}
    for n in vis_nodes:
        t = n["type"]
        if t not in node_groups:
            node_groups[t] = {
                "x": [], "y": [], "z": [],
                "ids": [], "labels": [], "colors": [], "hover": [],
            }
        p = pos.get(n["id"], [0, 0, 0])
        if n["id"] in broken_set:
            color = BROKEN_COLOR
        elif n["id"] in affected_set:
            color = AFFECTED_COLOR
        else:
            color = NODE_COLORS.get(t, "#888888")

        hover = f"<b>{n['label']}</b>  [{t}]"
        if n.get("path"):
            hover += f"<br><span style='color:#6e7681'>{n['path']}</span>"
        if n.get("lineno"):
            hover += f"<br>Line {n['lineno']}"
        if n.get("sig"):
            hover += f"<br><i style='color:#58a6ff'>{n['sig']}</i>"

        node_groups[t]["x"].append(p[0])
        node_groups[t]["y"].append(p[1])
        node_groups[t]["z"].append(p[2])
        node_groups[t]["ids"].append(n["id"])
        node_groups[t]["labels"].append(n["label"])
        node_groups[t]["colors"].append(color)
        node_groups[t]["hover"].append(hover)

    for ntype, data in node_groups.items():
        fig.add_trace(go.Scatter3d(
            x=data["x"], y=data["y"], z=data["z"],
            mode="markers",
            marker=dict(
                size=NODE_SIZES.get(ntype, 5),
                color=data["colors"],
                line=dict(width=0.5, color="rgba(255,255,255,0.15)"),
                opacity=0.92,
            ),
            text=data["hover"],
            customdata=data["ids"],
            hovertemplate="%{text}<extra></extra>",
            name=ntype,
            legendgroup=f"node_{ntype}",
            showlegend=True,
        ))

    _axis = dict(
        showgrid=False, zeroline=False, showticklabels=False,
        showspikes=False, backgroundcolor=BG,
    )
    fig.update_layout(
        paper_bgcolor=BG,
        scene=dict(
            xaxis=_axis, yaxis=_axis, zaxis=_axis,
            bgcolor=BG,
            uirevision="keep",
        ),
        font=dict(color=TEXT, family="Consolas, monospace", size=11),
        legend=dict(
            bgcolor="rgba(22,27,34,0.85)", bordercolor=BORDER,
            borderwidth=1, font=dict(size=10),
        ),
        margin=dict(l=0, r=0, t=0, b=0),
        uirevision="keep",
    )
    return fig


# ── Dash app ──────────────────────────────────────────────────────────────────
app = dash.Dash(__name__, title="Faultline — Dependency Graph")
app.config.suppress_callback_exceptions = True

_SS = {"padding": "12px 14px", "borderBottom": f"1px solid {BORDER}"}
_LS = {
    "fontSize": "9px", "textTransform": "uppercase", "letterSpacing": "0.1em",
    "color": DIM, "marginBottom": "8px", "fontWeight": "bold",
}


def _dot(color):
    return html.Span(style={
        "display": "inline-block", "width": "8px", "height": "8px",
        "borderRadius": "50%", "background": color,
        "marginRight": "7px", "flexShrink": "0",
    })


def _stat(label, color, ntype):
    return html.Div([
        _dot(color),
        html.Span(label, style={"fontSize": "11px"}),
        html.Span(
            str(counts.get(ntype, 0)),
            style={"marginLeft": "auto", "color": DIM, "fontSize": "11px"},
        ),
    ], style={"display": "flex", "alignItems": "center", "marginBottom": "4px"})


_INPUT_STYLE = {
    "width": "100%", "background": BG, "border": f"1px solid {BORDER}",
    "borderRadius": "4px", "color": TEXT, "padding": "5px 8px",
    "fontFamily": "Consolas, monospace", "fontSize": "11px",
    "outline": "none", "boxSizing": "border-box",
}

_BTN_BASE = {
    "width": "100%", "background": "transparent",
    "borderRadius": "4px", "padding": "6px", "cursor": "pointer",
    "fontFamily": "Consolas, monospace", "fontSize": "11px",
}


app.layout = html.Div([

    # ── Sidebar ───────────────────────────────────────────────────────────
    html.Div([

        html.Div([
            html.H1("FAULTLINE", style={
                "fontSize": "15px", "color": ACCENT,
                "letterSpacing": "0.06em", "margin": "0",
            }),
            html.P("Dependency Graph", style={"fontSize": "10px", "color": DIM, "margin": "3px 0 0"}),
        ], style={"padding": "14px", "borderBottom": f"1px solid {BORDER}"}),

        # Stats
        html.Div([
            html.Div("Stats", style=_LS),
            _stat("Files",     "#4dabf7", "file"),
            _stat("Classes",   "#51cf66", "class"),
            _stat("Functions", "#ffd43b", "function"),
            _stat("Methods",   "#ff922b", "method"),
            html.Div([
                _dot(BROKEN_COLOR),
                html.Span("Broken + Affected", style={"fontSize": "11px"}),
                html.Span("0", id="cnt-broken", style={
                    "marginLeft": "auto", "color": BROKEN_COLOR,
                    "fontWeight": "bold", "fontSize": "11px",
                }),
            ], style={"display": "flex", "alignItems": "center", "marginTop": "5px"}),
        ], style=_SS),

        # View selector
        html.Div([
            html.Div("View", style=_LS),
            dcc.RadioItems(
                id="view-radio",
                options=[
                    {"label": " Full Graph", "value": "full"},
                    {"label": " Functional Tree", "value": "func"},
                ],
                value="full",
                labelStyle={
                    "display": "block", "fontSize": "11px",
                    "marginBottom": "7px", "cursor": "pointer",
                },
                inputStyle={"marginRight": "6px", "accentColor": ACCENT},
            ),
            html.P(
                "Functional Tree hides files & imports — shows only classes, "
                "functions, and methods connected by calls and inheritance. "
                "Red = broken; pink = affected downstream.",
                style={"fontSize": "9px", "color": DIM, "marginTop": "5px", "lineHeight": "1.5"},
            ),
        ], style=_SS),

        # Search
        html.Div([
            html.Div("Search", style=_LS),
            dcc.Input(
                id="search-input", type="text",
                placeholder="Filter nodes by name…",
                debounce=True,
                style=_INPUT_STYLE,
            ),
        ], style=_SS),

        # Broken nodes list
        html.Div([
            html.Div("Broken Nodes", style=_LS),
            html.Div(id="broken-list",
                     style={"fontSize": "10px", "color": DIM, "minHeight": "16px"}),
            html.Button(
                "Reset All Broken", id="reset-btn",
                style={**_BTN_BASE, "marginTop": "8px",
                       "border": f"1px solid #f85149", "color": "#f85149"},
            ),
        ], style=_SS),

        # Selected node info
        html.Div([
            html.Div("Selected Node", style=_LS),
            html.Div(id="node-info",
                     style={"fontSize": "11px", "color": DIM, "minHeight": "20px"}),
            html.Button(
                "Mark as Broken", id="broken-btn", n_clicks=0,
                style={**_BTN_BASE, "marginTop": "8px",
                       "display": "none", "border": f"1px solid {BORDER}", "color": TEXT},
            ),
        ], style={**_SS, "flexGrow": "1"}),

    ], style={
        "width": "270px", "minWidth": "270px", "background": SURFACE,
        "borderRight": f"1px solid {BORDER}", "overflowY": "auto",
        "height": "100vh", "display": "flex", "flexDirection": "column",
    }),

    # ── Graph ─────────────────────────────────────────────────────────────
    html.Div([
        dcc.Graph(
            id="main-graph",
            figure=build_figure("full", []),
            style={"height": "100vh"},
            config={
                "displayModeBar": True,
                "modeBarButtonsToRemove": ["select2d", "lasso2d"],
                "displaylogo": False,
                "toImageButtonOptions": {"format": "png", "width": 1920, "height": 1080},
            },
        ),
    ], style={"flex": "1", "overflow": "hidden"}),

    # ── Stores ────────────────────────────────────────────────────────────
    dcc.Store(id="broken-store", data=[]),
    dcc.Store(id="selected-store", data=None),

], style={
    "display": "flex", "height": "100vh",
    "background": BG, "color": TEXT,
    "fontFamily": "Consolas, monospace", "overflow": "hidden",
})


# ── Callbacks ─────────────────────────────────────────────────────────────────

@app.callback(
    Output("selected-store", "data"),
    Input("main-graph", "clickData"),
    State("selected-store", "data"),
    prevent_initial_call=True,
)
def on_click(click_data, current):
    if not click_data:
        return current
    point = click_data["points"][0]
    nid = point.get("customdata")
    return nid if nid else current


@app.callback(
    Output("broken-store", "data"),
    Input("broken-btn", "n_clicks"),
    Input("reset-btn", "n_clicks"),
    State("selected-store", "data"),
    State("broken-store", "data"),
    prevent_initial_call=True,
)
def toggle_broken(mark_n, reset_n, selected, broken):
    triggered = ctx.triggered_id
    if triggered == "reset-btn":
        return []
    if triggered == "broken-btn" and selected:
        broken = list(broken or [])
        if selected in broken:
            broken.remove(selected)
        else:
            broken.append(selected)
        return broken
    return broken or []


@app.callback(
    Output("main-graph", "figure"),
    Output("cnt-broken", "children"),
    Input("broken-store", "data"),
    Input("view-radio", "value"),
    Input("search-input", "value"),
)
def update_graph(broken, view, search):
    broken = broken or []
    affected = bfs_affected(set(broken))
    fig = build_figure(view or "full", broken, search or "")
    return fig, str(len(broken) + len(affected))


@app.callback(
    Output("node-info", "children"),
    Output("broken-btn", "children"),
    Output("broken-btn", "style"),
    Input("selected-store", "data"),
    Input("broken-store", "data"),
)
def update_info(selected, broken):
    broken = set(broken or [])
    hidden = {**_BTN_BASE, "display": "none", "border": f"1px solid {BORDER}", "color": TEXT}
    if not selected:
        return html.Span("Click a node to inspect it.", style={"color": DIM}), "Mark as Broken", hidden

    n = node_map.get(selected)
    if not n:
        return html.Span("Node not found."), "Mark as Broken", hidden

    is_broken   = selected in broken
    badge_color = NODE_COLORS.get(n["type"], "#888")
    info = html.Div([
        html.Span(
            n["type"].upper(),
            style={
                "fontSize": "8px", "background": "#1c2d40", "color": badge_color,
                "padding": "2px 8px", "borderRadius": "10px",
                "letterSpacing": "0.08em", "fontWeight": "bold",
            },
        ),
        html.Div(n["label"], style={
            "fontSize": "13px", "fontWeight": "bold", "color": TEXT,
            "marginTop": "6px", "marginBottom": "3px", "wordBreak": "break-all",
        }),
        html.Div(n.get("path", ""), style={"fontSize": "9px", "color": DIM}),
        html.Div(f"Line {n['lineno']}" if n.get("lineno") else "",
                 style={"fontSize": "9px", "color": DIM}),
        html.Div(n.get("sig", ""), style={
            "fontSize": "9px", "color": ACCENT,
            "wordBreak": "break-all", "marginTop": "3px",
        }),
    ])
    btn_color = "#f85149" if is_broken else ACCENT
    btn_label = "Clear Broken" if is_broken else "Mark as Broken"
    return (
        info,
        btn_label,
        {**_BTN_BASE, "display": "block", "border": f"1px solid {btn_color}", "color": btn_color},
    )


@app.callback(
    Output("broken-list", "children"),
    Input("broken-store", "data"),
)
def update_broken_list(broken):
    broken = broken or []
    if not broken:
        return html.Span("None marked.", style={"color": DIM})
    items = []
    for nid in broken[:12]:
        n = node_map.get(nid)
        items.append(html.Div(
            f"• {n['label'] if n else nid}",
            style={"color": BROKEN_COLOR, "marginBottom": "2px", "fontSize": "10px"},
        ))
    if len(broken) > 12:
        items.append(html.Div(
            f"…and {len(broken) - 12} more",
            style={"color": DIM, "fontSize": "10px"},
        ))
    return items


if __name__ == "__main__":
    import threading, webbrowser
    print("\nFaultline Dependency Graph")
    print("=" * 40)
    print("Open: http://localhost:8050")
    print("Stop: Ctrl+C\n")
    threading.Timer(1.2, lambda: webbrowser.open("http://localhost:8050")).start()
    app.run(debug=False, host="127.0.0.1", port=8050)
"""


# ─────────────────────────────────────────────────────────────────────────────
# Generator
# ─────────────────────────────────────────────────────────────────────────────

class Graph3DGenerator:
    """Converts enriched ASTGrapher output into a self-contained Dash app script."""

    def generate(self, graph_data: dict, output_path: str) -> str:
        """
        Build the node/link lists, compute layouts, write the Dash app script.
        Returns the path to the generated .py file.
        """
        nodes, links = self._build(graph_data)

        pos_full = _compute_layout(nodes, links, mode="full")
        pos_func = _compute_layout(nodes, links, mode="func")

        sep = ","
        script = _TEMPLATE
        script = script.replace("__NODES__",    json.dumps(nodes,    separators=(sep, ":")))
        script = script.replace("__LINKS__",    json.dumps(links,    separators=(sep, ":")))
        script = script.replace("__POS_FULL__", json.dumps(pos_full, separators=(sep, ":")))
        script = script.replace("__POS_FUNC__", json.dumps(pos_func, separators=(sep, ":")))

        # Always output as a .py file
        out = Path(output_path)
        if out.suffix.lower() != ".py":
            out = out.with_suffix(".py")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(script, encoding="utf-8")
        return str(out)

    # ─────────────────────────────────────────────────────────────────────
    # Build node + link lists from ASTGrapher output
    # ─────────────────────────────────────────────────────────────────────

    def _build(self, graph_data: dict):
        nodes: list[dict] = []
        links: list[dict] = []
        node_ids: set[str] = set()
        link_keys: set[tuple] = set()

        def add_node(n: dict):
            if n["id"] not in node_ids:
                node_ids.add(n["id"])
                nodes.append(n)

        def add_link(src: str, tgt: str, ltype: str):
            key = (src, tgt, ltype)
            if key not in link_keys and src in node_ids and tgt in node_ids:
                link_keys.add(key)
                links.append({"source": src, "target": tgt, "type": ltype})

        sigs = graph_data.get("signatures", {})

        ser_map: dict[str, list] = {}
        for s in (graph_data.get("serializer_schemas") or []):
            ser_map[s["class_id"]] = s["fields"]

        for fp, fi in graph_data.get("files", {}).items():
            if isinstance(fi, dict) and fi.get("error"):
                continue

            file_id = f"file:{fp}"
            add_node({"id": file_id, "type": "file",
                       "label": Path(fp).name, "path": fp,
                       "group": str(Path(fp).parent)})

            for cls in (fi.get("classes") or []):
                cls_id  = f"class:{fp}:{cls['name']}"
                node_d: dict = {
                    "id": cls_id, "type": "class",
                    "label": cls["name"], "path": fp,
                    "lineno": cls.get("lineno"), "group": fp,
                }
                if cls_id in ser_map:
                    node_d["serializer_fields"] = ser_map[cls_id]
                add_node(node_d)
                add_link(file_id, cls_id, "contains")

                for method in (cls.get("methods") or []):
                    mid = f"method:{fp}:{cls['name']}.{method}"
                    sig = sigs.get(mid, {})
                    add_node({"id": mid, "type": "method",
                               "label": method, "path": fp,
                               "group": f"{fp}:{cls['name']}",
                               "sig": sig.get("sig_str", "")})
                    add_link(cls_id, mid, "contains")

            for fn in (fi.get("functions") or []):
                fid = f"func:{fp}:{fn['name']}"
                sig = sigs.get(fid, {})
                add_node({"id": fid, "type": "function",
                           "label": fn["name"], "path": fp,
                           "lineno": fn.get("lineno"), "group": fp,
                           "sig": sig.get("sig_str", "")})
                add_link(file_id, fid, "contains")

        for src, tgt in (graph_data.get("dependencies") or []):
            add_link(f"file:{src}", f"file:{tgt}", "imports")

        for e in (graph_data.get("call_edges") or []):
            add_link(e["source"], e["target"], "calls")

        for e in (graph_data.get("inheritance_edges") or []):
            add_link(e["source"], e["target"], "inherits")

        return nodes, links
