# Generated by Django 5.2.13 on 2026-04-29 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('auth_type', models.CharField(choices=[('static', 'Static Token'), ('login', 'Login Endpoint')], default='login', max_length=20)),
                ('auth_url', models.CharField(blank=True, help_text='Relative or absolute URL for authentication (e.g. /api/login)', max_length=512)),
                ('auth_method', models.CharField(default='POST', max_length=10)),
                ('auth_payload', models.JSONField(blank=True, help_text='JSON payload to send (e.g. email/password). If STATIC_TOKEN, this can just be the token string.', null=True)),
                ('token_extraction_path', models.CharField(blank=True, help_text="JSON path or simple key to extract the token from the response (e.g. 'access_token' or 'data.token')", max_length=255)),
                ('injection_type', models.CharField(choices=[('header', 'Header'), ('cookie', 'Cookie')], default='header', max_length=20)),
                ('injection_key', models.CharField(default='Authorization', help_text="e.g. 'Authorization' or 'session_id'", max_length=120)),
                ('injection_format', models.CharField(default='Bearer {token}', help_text='Format string. Use {token} as placeholder.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
