# Generated by Django 5.2.13 on 2026-04-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='vision_step',
            field=models.PositiveIntegerField(blank=True, help_text='Maps to the 1-7 step Vision pipeline', null=True),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='vision_step',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
